#! /bin/bash

newline=0
if [ "x$1" == "x-n" ]; then
  newline=1
  shift
fi

hosts=`echo blc{0..7}{0..7}`
for i in $hosts; do
    if [ $newline -eq 1 ]; then
      echo -n $i" : "
    else
      echo $i =========================
    fi
    ssh -o BatchMode=yes -o ConnectTimeout=1 $i "$1"
done
