#! /bin/bash

RADECFIX=/home/obs/bin/fix_ra_dec.py
MYSQLCMD="mysql -N -u obs -h 104.154.94.28 BLtargets"

if [ "x" == "x$1" ]; then
  echo "chain_fixup gb_filterbank_file_to_fix_ra_dec_fch1.fil"
  exit 0
fi

filfile=$1

echo "File: $filfile"
mjd=`/home/obs/bin/header_wrapper $filfile | grep MJD | awk '{print $NF}'`

if [ -z "$mjd" ]
then
    echo "could not extract header data, file appears to be corrupted"
    exit 1
fi

echo "Reading ra/dec from database:"
query='select target_name,ra_hrs,dec_deg from go_scans where abs(((unix_timestamp(utc_observed)/86400)+40587)-'$mjd') < 0.0002;'
output=`echo $query | $MYSQLCMD | sed 's/\t/,/g'`
newra=`echo $output | awk -F, '{print $2}' | cut -d' ' -f1`
newdec=`echo $output | awk -F, '{print $3}' | cut -d' ' -f1`

if [ "x" == "x$newdec" ] ; then
  echo "cannot find target in go_scans database - bailing..."
  exit 0
fi

$RADECFIX $newra $newdec $filfile || exit 1
echo =================================================================
