#! /bin/csh

set FULL = `all_nodes_bg -n "df -h /datax | grep datax" | sed 's/%//' | awk '$7>72' | wc -l`
set GPUSPEC = `/home/obs/bin/all_ps gpuspec | grep -v ============== | wc -l`

if ($FULL > 0 && $GPUSPEC == 0) then
  mail -s "WARNING: GB disks full and reduction is not running" lebofsky@berkeley.edu < /dev/null
endif

