#! /bin/csh

if (x == x$1) then
  echo "which root directory?"
  exit 1
endif

set BASENAME = `basename $1`
foreach h (2 3 4 5)
  sudo ssh  -o BatchMode=yes -o ConnectTimeout=1 blc$h '/home/obs/bin/rewrite '$1' >& /home/obs/logs/rewrite.out.blc'$h'.'$BASENAME &
end  
