#! /bin/bash

# echo "turned off temporarily (talk to matt)"
# exit 0

topdir=$1
shift
hosts="${@:-$(echo blc{0..7}{0..7})}"

if [ "$topdir" == "" -o "$topdir" == "-h" -o "$topdir" == "--help" ]; then
  echo "which root directory?"
  echo " "
  echo "usage: do_all_rawspec root_directory [hosts]"
  echo '   hosts defaults to: blc{0..7}{0..7}'
  exit 1
fi

basename=`basename $topdir`

for host in $hosts; do
  echo starting rawspec on ${host}:$topdir
  sudo ssh  -o BatchMode=yes -o ConnectTimeout=1 $host '/home/obs/bin/do_rawspec_special_0003 '$topdir' >& /home/obs/logs/do_rawspec_special_0003.out.'$host'.'${basename}.$$ &
done
