#! /bin/csh

if (x == x$1) then
  echo "which root directory?"
  exit 1
endif

foreach h (0 1 2 3 4 5 6 7)
  ssh blc$h '/home/obs/bin/rewrite_8to2 '$1' >& /home/obs/logs/rewrite_8to2.out.blc'$h &
end  
