#! /bin/csh

if (x == x$1) then
  echo "which root directory?"
  exit 1
endif

set BASENAME = `basename $1`
foreach r (0 1)
  foreach h (0 1 2 3 4 5 6 7)
    sudo ssh  -o BatchMode=yes -o ConnectTimeout=1 blc$r$h '/home/obs/bin/do_ratan_gpuspec '$1' >& /home/obs/logs/do_ratan_gpuspec.out.blc'$r$h'.'$BASENAME &
  end  
end
