#! /bin/csh

if (x == x$1) then
  echo "which root directory?"
  exit 1
endif

foreach h (0 1 2 3 4 5 6 7)
  ssh  -o BatchMode=yes -o ConnectTimeout=1 blc$h '/home/obs/bin/rewrite '$1' >& /home/obs/logs/rewrite.out.2.blc'$h &
end  
