#! /bin/csh

set TRIGGERFILE = /home/obs/triggers/stop_anyspec_collate

if (x == x$2) then
  echo do_anyspec_collate dir collate_dir
  echo "  try to collate everything in dir and put products into collate_dir" 
  exit 0
endif

cd $1

foreach i (` ls -1 *spec.done *.0000.fil | awk -F/ '{print $NF}' | sed 's/blc[0-9]_//' | sed 's/blc[0-9][0-9]_//' | sed 's/.[a-z][a-z][a-z]spec.done//' | sed 's/.[a-z][a-z][a-z]spec.0000.fil//' | sort | uniq -c | awk '$1==2 {print $2}'`)
  if ( -f $TRIGGERFILE ) then
    echo "stopping because $TRIGGERFILE exists..."
    exit 0
  endif
  echo -n $i" - starting : "
  date
  /home/obs/bin/anyspec_collate $i $2
  echo -n "finished $i : "
  date
  echo ===============================================
end
