#! /bin/csh

if (x == x$1) then
  echo "which root directory?"
  exit 1
endif

set BASENAME = `basename $1`
# foreach r (1)
#   foreach h (1)
#   foreach h (0 1 3 4 5 6 7)
# foreach r (0)
#foreach r (0 1 2)
foreach r (0)
  foreach h ( 2 3 4 5 )
#    if ($r == 1 && $h == 3) then
#      echo "skipping blc$r$h ..."
#    else 
      echo "starting on blc$r$h ..."
      sudo ssh  -o BatchMode=yes -o ConnectTimeout=1 blc$r$h '/home/obs/bin/make_sah '$1' >& /home/obs/logs/make_sah.out.blc'$r$h'.'${BASENAME}.$$ &
#    endif
  end  
end
