#! /bin/csh

if (x == x$2) then
  echo do_rawspec_0003_collate dir collate_dir
  echo "  try to collate everything in dir and put products into collate_dir" 
  exit 0
endif

cd $1

# foreach i (` ls -1 *.gpuspec.done *.0000.fil | awk -F/ '{print $NF}' | sed 's/blc[0-9]_//' | sed 's/blc[0-9][0-9]_//' | sed 's/.gpuspec.done//' | sed 's/.gpuspec.0000.fil//' | sort | uniq -c | awk '$1==2 {print $2}'`)
foreach i (` ls -1 *.rawspec.0003.fil | awk -F/ '{print $NF}' | sed 's/blc[0-9]_//' | sed 's/blc[0-9][0-9]_//' | sed 's/.rawspec.0003.fil//'`)
  echo -n $i" - starting : "
  date
  /home/obs/bin/rawspec_0003_collate $i $2
  echo -n "finished $i : "
  date
  echo ===============================================
end
