#! /bin/csh

# do_rawspec top_data_dir [hostname_override]

# scan for all .raw files under top_data_dir and run rawspec on all possible data

# if we aren't observing (as dictated by the contents of file $OBSERVINGSTATUS) and
#    we aren't already running (as dictated by the existence of $HOSTRUNNING trigger file) then
#    * fire off a rawspec loop on all potential raw data (basically ever observation that starts with *.0000.raw)
#      * check to see if $TRIGGER exists (human may create it to stop all rawspecs) - if so, exit
#      * run bl_fixup.rb on all the respective .raw files of this observation
#      * run rawspec with parameters based on 2 or 8 bit data, and block size of raw data
#      * run an 8-bitter on the pulsar product 
#      * if no "DIAG" string found in the path, check file sized of .fil products - if sane, delete .raw files
#

##### PARKES/cuda-8.0
setenv PATH /usr/local/cuda-8.0/bin:$PATH
setenv LD_LIBRARY_PATH /usr/local/cuda-8.0/lib64:/usr/local/listen/lib

set TRIGGER = /home/obs/triggers/stop_rawspec
# set TRIGGER = /home/obs/triggers/stop_rawspec_NOT_REALLY # uncomment this is you want it to run whenever
set SAH_HOSTS = /home/obs/triggers/sah_hosts
set RAWQUANTEXE = /usr/local/listen/bin/raw_quant

set OBSERVINGSTATUS = /home/obs/triggers/observation_status

#set GPUSPECEXE = /usr/local/listen/bin/gpuspec
set GPUSPECEXE = /usr/local/listen/bin/gpuspec2

set RAWSPECEXE = /usr/local/bin/rawspec

set TMPFILE = /tmp/rawspec.tmp.$$

set TWOBITBLOCKSIZE = 33069312

if (x == x$1) then
  echo "which root directory?"
  exit 1
endif

if (x == x$2) then
  set HOSTNAME = `hostname`
else 
  set HOSTNAME = $2
endif

set ISCRON = "no"

set THISDIR = `pwd`

set HOSTRUNNING = /home/obs/triggers/rawspec_${HOSTNAME}_running

if (-f $HOSTRUNNING) then
  # only report if not in a cron job (otherwise log will get noisy)
  if ($ISCRON == "no") then 
    echo "rawspec is already running on host $HOSTNAME - exiting..."
    echo "remove triggerfile: $HOSTRUNNING if you feel this is bogus"
    echo " "
    echo "output of pgrep -fl rawspec:"
    echo " "
    pgrep -fl rawspec
  endif
  exit 1
endif

touch $HOSTRUNNING

foreach i (`find $1 -name "*guppi*raw" -print | sed 's/.[0-9][0-9][0-9][0-9].raw//' | sort | uniq`)

  if (-f $TRIGGER) then
    echo "stopping because triggerfile: $TRIGGER exists..."
    rm $HOSTRUNNING
    exit 0
  endif

  cd $THISDIR

  set BASENAME = `basename $i`
  set DIRNAME = `dirname $i`

  cd $DIRNAME

  echo $i
  echo =====================================================================

  set START = `date '+%s'`
  echo -n "starting: "
  date

  set GSERROR = 0

  set BITS = 8
  set TWOBIT = `ls ${BASENAME}.[0-9][0-9][0-9][0-9].raw |& grep -c "_2bit"`
  if ($TWOBIT > 0) then
    set BITS = 2
  endif
  echo "setting bit depth to $BITS"

  # is the a _999_ set? 1 = yes, 0 = no 
  set ISBL = `fold -w 80 *raw | head -80 | grep -a PROJID | grep -c _999_`

  set BLOCSIZE = `fold -w 80 *raw | head -80 | grep -a BLOCSIZE | awk '{print $2}'`
  echo BLOCSIZE : $BLOCSIZE
  # original version if BLOCSIZE = 132251648
  set PRODUCTS = "-f 1033216,8,1024 -t 51,128,3027"
  if ($BLOCSIZE == 134217728) then
    set PRODUCTS = "-f 1048576,8,1024 -t 51,128,3072"
#    set PRODUCTS = "-f 1048576,8,1024 -t 3,128,3072" # for one second high freq resolution!
  endif
  if ($BLOCSIZE == 129499136) then
    set PRODUCTS = "-f 999424,8,1024 -t 51,128,2928"
  endif

  if (-f ${BASENAME}.rawspec.0003.fil && ! -z ${BASENAME}.rawspec.0030.fil) then
    echo ".fil files exist - already reduced - skipping fixup/rawspec..."
  else 

    echo "running 0003.fil -- rawspec -p 1 -f 32 -t 4 -0 3"
    echo -n "starting: "
      date
      $RAWSPECEXE $i -p 1 -f 32 -t 4 -o 3 
      echo -n "ending : "
      date
    endif

  endif # already rawspec'ed

end

# no more files - show's over - remove running trigger and exit
rm $HOSTRUNNING
