#! /bin/csh

if (x == x$2) then
  echo do_rawpsec_collate dir collate_dir
  echo "  try to collate everything in dir and put products into collate_dir" 
  exit 0
endif

cd $1

foreach i (` ls -1 *.rawspec.done *.0000.fil | awk -F/ '{print $NF}' | sed 's/blc[0-9]_//' | sed 's/blc[0-9][0-9]_//' | sed 's/.rawspec.done//' | sed 's/.rawspec.0000.fil//' | sort | uniq -c | awk '$1==2 {print $2}'`)
  echo -n $i" - starting : "
  date
  /home/obs/bin/rawspec_collate $i $2
  echo -n "finished $i : "
  date
  echo ===============================================
end
