#! /bin/csh

set TMPFILE = /tmp/test_drives.$$

echo enc slt dev firmware_state
foreach i (`megacli -pdlist -a0 | awk '$1 == "Slot" && $2 == "Number:" {printf("%s:",$3)}; $1 == "Enclosure" && $2 == "Device" {printf("%s:",$4)}; $1 == "Device" && $2 == "Id:" {printf("%s:",$3)}; $1 == "Firmware" && $2 == "state:" {printf("%s\n",$3)}'`)
  set ENC = `echo $i | awk -F: '{print $1}'`
  set SLOT = `echo $i | awk -F: '{print $2}'`
  set DEV = `echo $i | awk -F: '{print $3}'`
  set FWS = `echo $i | awk -F: '{print $4}'`

  echo $ENC $SLOT $DEV $FWS | awk '{printf("%3d%4d%4d %s\n",$1,$2,$3,$4)}'
end

/bin/rm -f $TMPFILE
