#! /bin/bash

for i in bls{0..9} blc{0..7}{0..7}; do 
  for part in datax datax2 datax3; do
      # echo -n ${i}:${part} - 
      cd /mnt_$i/$part |& grep -v "No such file or" 2>&1 | awk -F"cd: " '{printf("%s\n",$2)}'
      cd /mnt_$i/$part |& grep -v "No such file or" 2>&1 ; df /mnt_$i/$part |& grep -v '^df: ' | tail -1 | awk '$NF == "/" {printf("'${i}:${part}' - not mounted\n")}' | grep -v 'blc[0-9][0-9]:datax3'
  done
done
