#! /bin/bash

source /usr/local/pulsar64/pulsar.bash
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib

# cd /datax/dibas/AGBT17A_999_56/GUPPI/*
# cd /datax/dibas.20170406/AGBT17A_999_40/GUPPI/*
# cd /datax2/from_datax/dibas.20170406/AGBT17A_999_40/GUPPI/*
# cd /datax/dibas/AGBT17A_999_60/GUPPI/*
cd /datax/dibas/AGBT17A_999_62/GUPPI/BLP2?

for thisfile in guppi_57880_31473_DIAG_2MASS_1501+2250_0001; do

  INFILE=`hostname`_$thisfile

  for i in 0 1 3; do 
    numactl --cpunodebind 1 ~siemion/sw/dev/gbt_seti/src/gpuspec2 -i ${INFILE}.*.raw -p $i -b 8 -B 2 -f 1024 -t 3072 -o ${INFILE}.p${i}.gpuspec.
  done

done
