#! /bin/csh

#if (`hostname` != "bls0") then
#  echo "must be on bls0 to run this"
#  exit 1
#endif

set TMPFILE = /tmp/gpuspec_inventory.$$

find /mnt_bl* -name "*.gpuspec.done" > $TMPFILE

foreach i (`cat $TMPFILE | awk -F/ '{print $NF}' | sed 's/blc[0-9]_//' | sed 's/blc[0-9][0-9]_//' | sed 's/.gpuspec.done//' | sort | uniq`)
  echo -n $i" : "
  set COUNT = `grep -c $i $TMPFILE`
  foreach j (`grep $i $TMPFILE`)
    set NODE = `echo $j | awk -F/ '{print $NF}' | awk -F_ '{print $1}' | sed 's/blc//'`
    echo -n $NODE" "
  end
  echo "( total : $COUNT )"
end

/bin/rm $TMPFILE
