#! /bin/bash

TMPFILE=/tmp/header_wrapper.$$
REALPATH=`echo $(cd $(dirname "$1") && pwd -P)/$(basename "$1")`
ln -s $REALPATH $TMPFILE
/usr/local/sigproc/bin/headeredit $TMPFILE ${@:2}
/bin/rm -r $TMPFILE
