#! /bin/bash
# finds the last 0005 file
hosts="${@:-$(echo blc{0..0}{0..7})}"

for h in $hosts; do ssh -x -o BatchMode=yes -o ConnectTimeout=1 $h 'ls -ltr /datax/dibas/AGBT1??_999_*/GUPPI/*/*0005.raw | tail -1' ; done
