#! /bin/bash

# am i (the hosts) not in hosts_running file? then exit
hostname=`hostname`
infile=`grep -c $hostname /home/obs/triggers/hosts_running`
if [ $infile == 0 ]; then
  exit 0
fi

MOSTRECENT=`ls -trd /datax/dibas/?GBT1??_999_* | tail -1 `
ls $MOSTRECENT/*/*/guppi*0000.raw |& grep -v "cannot access" | awk -Fguppi_ '{print $2}' | sed 's/^[0-9][0-9][0-9][0-9][0-9]_[0-9][0-9][0-9][0-9][0-9]_//' | sed 's/.[0-9][0-9][0-9][0-9].raw//'
